version: '3.3'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb-chat'
    restart: 'always'
    ports:
      - '27017:27017'
    networks:
      - chat-api-networks
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 20s
      timeout: 10s
      retries: 5
  chat-api:
    image: 'chat-api:latest'
    container_name: 'chat-api'
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
      SPRING_DATA_MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - chat-api-networks
    ports:
      - '8080:8080'
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb
  prometheus:
    image: 'prom/prometheus:latest'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - chat-api-networks
    ports:
      - '9090:9090'
  grafana:
    image: 'grafana/grafana:latest'
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - chat-api-networks
    depends_on:
      prometheus:
        condition: service_started
    links:
      - prometheus

networks:
  chat-api-networks:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: