spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      host: 'mongodb'
jwt:
  secret: ${JWT_SECRET}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      enabled: true
      show-details: 'always'
    prometheus:
      enabled: true
